fix(ci): make sure the done stage can act as a proper flag that we successfully release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -130,12 +130,19 @@
           docker manifest push ghcr.io/gh-org-template/template-1-github-release:${{ needs.release.outputs.release-git-tag }}-${{ matrix.ostype }}
 
     done:
-      needs: [artifacts]
+      needs: [release, artifacts, multi-arch]
       name: Done
       if: needs.artifacts.result == 'success'
       runs-on: ubuntu-latest
       steps:
-      - run: echo 'done'
+      - name: Check for Failed Jobs
+        run: |
+          if [[ "${{ needs.release.result }}" == "failure" || "${{ needs.artifacts.result }}" == "failure" || "${{ needs.multi-arch.result }}" == "failure" ]]; then
+            echo "One or more jobs failed. Marking release as failed."
+            exit 1
+          else
+            echo "All jobs succeeded or were skipped. Marking release as successful."
+          fi
 
     cleanup:
       needs: [release]
