fix(ci): logic to handle failed releases (#21)
* fix(ci): if we half-release because of rate limits delete the release

* fix(ci): make sure the done stage can act as a proper flag that we successfully release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -130,9 +130,34 @@
           docker manifest push ghcr.io/gh-org-template/template-1-github-release:${{ needs.release.outputs.release-git-tag }}-${{ matrix.ostype }}
 
     done:
-      needs: [artifacts]
+      needs: [release, artifacts, multi-arch]
       name: Done
       if: needs.artifacts.result == 'success'
       runs-on: ubuntu-latest
       steps:
-      - run: echo 'done'
+      - name: Check for Failed Jobs
+        run: |
+          if [[ "${{ needs.release.result }}" == "failure" || "${{ needs.artifacts.result }}" == "failure" || "${{ needs.multi-arch.result }}" == "failure" ]]; then
+            echo "One or more jobs failed. Marking release as failed."
+            exit 1
+          else
+            echo "All jobs succeeded or were skipped. Marking release as successful."
+          fi
+
+    cleanup:
+      needs: [release]
+      if: failure()
+      name: Cleanup Half-Created Release/Tag
+      runs-on: ubuntu-latest
+      steps:
+      - name: Delete GitHub Release
+        run: |
+          if gh release view ${{ needs.release.outputs.release-git-tag }} >/dev/null 2>&1; then
+            gh release delete ${{ needs.release.outputs.release-git-tag }} --yes
+          fi
+      - name: Delete GitHub Tag
+        run: |
+          if git show-ref --tags ${{ needs.release.outputs.release-git-tag }}; then
+            git tag -d ${{ needs.release.outputs.release-git-tag }}
+            git push origin :refs/tags/${{ needs.release.outputs.release-git-tag }}
+          fi
